version: 0.2
phases:
  build:
    commands:
      - echo Packing JAR file...
      - mvn clean package
    post_build:
      commands:
        - echo Build complete.
artifacts:
  files:
    - target/app.jar
discard:paths: yes